### ISSUE TITLE
device import missing from objects.py

### ISSUE THREAD

**Issue by noziwatele** [HPENetworking/PYHPEIMC#22]
Hey netmanchris,
Firstly, thanks for all your work on this IMC API client! We have IMC here and I am looking at using this for a bit of automation work that we're doing.

I have come across a few issues when working with the IMCDev and IMCInterface classes in objects.py. Unless I'm missing something, it looks like there's an import statement missing for the device.py file, as follows:

`from pyhpeimc.plat.device import *`

Without this I get: NameError: name 'get_dev_interface' is not defined

Once I add in this import, I get a few more errors around arguments that seem to be in a different order between objects.py and device.py. Starting from line 95, "self.interfacelist", the auth, url, and self.devid attributes are in a different order.

I have made some updates to the code locally and would be happy to contribute if you like.

Cheers,
Mike.

**Comment by netmanchris** [comment]
Hey @noziwatele 

Glad you're finding this useful!  Unfortunately, due to legal issues, we can't accept external contributions from non-HPE people without going through paperwork. But... if you can let me know what issues you're seeing and what you would like to see I'd be more than happy to make the necessary modifications. 

If there's any more info you think will be helpful to get this working for, please feel free to provide it. In the mean time I'll take a look and see if I can fix what you're seeing.

**Comment by netmanchris** [comment]
Hey @noziwatele 

TL/DR: Fixed objects module and pushed pyhpeimc 1.0.39 to Pypi. Should address issues. 

Updated source code to fix imports and the existing class objects to get you through the reported issue. I need to add tests specific to the objects module to the testframework but that's going to take a little more time.  

If you have any other issues, please feel free to reach out! 

@netmanchris
